import os, shutil

root = "centauri"
sections = {
    "A_Origin_Vector": [
        "CIS-A1-PDM_Problem_Definition_Matrix.md",
        "CIS-A2-SFS_Scientific_Foundations_Scan.md",
        "CIS-A3-CHS_Concept_Hypothesis_Sheet.md",
        "CIS-A4-FEM_Feasibility_Envelope_Model.md",
        "CIS-A5-UID_Umbrella_Integration_Draft.md",
    ],
    "B_Seed_Vector": [
        "CIS-B1-PAB_Preliminary_Architecture_Blueprint.md",
        "CIS-B2-MBL_Mirror_Base_Lattice_Map.md",
        "CIS-B3-A0R_Prototype_Alpha0_Report.md",
        "CIS-B4-RFMA_Risk_Failure_Mode_Atlas.md",
        "CIS-B5-SP1G_SBIR_Phase1_Readiness_Gate.md",
    ],
    "C_Ignition_Vector": [
        "CIS-C1-P1WA_Phase1_Workplan_Activation.md",
        "CIS-C2-A1R_Prototype_Alpha1_Report.md",
        "CIS-C3-EVL_Experimental_Validation_Log.md",
        "CIS-C4-MID_Mission_Interface_Draft.md",
        "CIS-C5-P1CA_Phase1_Closeout_TRL_Audit.md",
    ],
    "D_Ascent_Vector": [
        "CIS-D1-P2SEP_Phase2_Systems_Engineering_Plan.md",
        "CIS-D2-B0R_Prototype_Beta0_Report.md",
        "CIS-D3-PGMIS_Pass_Glass_Morphism_Integration_Spec.md",
        "CIS-D4-EQP_Environmental_Qualification_Pathway.md",
        "CIS-D5-MOSTL_Mission_Ops_Simulation_Trial_Log.md",
    ],
    "E_Orbit_Vector": [
        "CIS-E1-B1R_Prototype_Beta1_Report.md",
        "CIS-E2-EILM_Extended_Infrastructure_Layer_Map.md",
        "CIS-E3-MSSTR_Mission_Scenario_Stress_Test_Report.md",
        "CIS-E4-LORR1_Lunar_Ops_Readiness_Review.md",
        "CIS-E5-CVD_Commercialization_Vector_Draft.md",
    ],
    "F_Translunar_Vector": [
        "CIS-F1-G0R_Prototype_Gamma0_Report.md",
        "CIS-F2-MICP_Mission_Integration_Certification_Packet.md",
        "CIS-F3-ODI_Operational_Deployment_Index.md",
        "CIS-F4-CSE_Commercialization_Scaling_Engine.md",
        "CIS-F5-CAR_Centauri_Apex_Review.md",
    ],
}

file_contents = {}

# A1 - A5
file_contents["CIS-A1-PDM_Problem_Definition_Matrix.md"] = """# Problem Definition Matrix\n\n**Document ID:** CIS-A1-PDM\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-0\n**TRL Target:** 1\n**Grid Slot:** U-001\n**PRECISELIENS Node:** Glass-0\n\n---\n\n## 1. Purpose\nDefine the mission need, operational constraints, and lunar relevance for the candidate technology. Establish the foundational problem statement that drives all downstream Centauri phases.\n\n## 2. Inputs\n- Artemis mission objectives\n- ConOps documentation\n- Known capability gaps\n- Environmental constraints (thermal, vacuum, dust, radiation)\n\n## 3. Outputs\n- Mission Need Statement (MNS)\n- Constraint matrix\n- Initial success criteria\n- Problem framing narrative\n\n## 4. Method\n1. Extract mission drivers from ConOps.\n2. Identify explicit and implicit capability gaps.\n3. Translate gaps into structured problem statements.\n4. Validate with cross-discipline review.\n\n## 5. Mission Integration\n- Maps to Artemis surface operations\n- Identifies EVA, logistics, and comms dependencies\n- Establishes early integration hooks\n\n## 6. TRL & SBIR Mapping\n- TRL: 1\n- SBIR: Pre-Phase I ideation\n\n## 7. Risks & Mitigations\n- **Risk:** Misalignment with evolving mission priorities\n  **Mitigation:** Refresh at each major review\n- **Risk:** Overly narrow framing\n  **Mitigation:** Include multi-domain review\n\n## 8. Change Log\n- 2026-05-17 — Initial creation\n"""
file_contents["CIS-A2-SFS_Scientific_Foundations_Scan.md"] = """# Scientific Foundations Scan\n\n**Document ID:** CIS-A2-SFS\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-1\n**TRL Target:** 1\n**Grid Slot:** U-002\n**PRECISELIENS Node:** Glass-1\n\n---\n\n## 1. Purpose\nSurvey scientific literature, NASA tech gap reports, and mission needs to establish the theoretical basis for the technology.\n\n## 2. Inputs\n- NASA Tech Gap Database\n- Peer-reviewed literature\n- Mission architecture documents\n- Prior SBIR awards\n\n## 3. Outputs\n- Scientific gap map\n- Foundational citations\n- Relevance justification\n- Early feasibility indicators\n\n## 4. Method\n1. Conduct literature review\n2. Extract relevant principles\n3. Map principles to mission needs\n4. Identify unresolved scientific questions\n\n## 5. Mission Integration\n- Aligns scientific basis with Artemis mission phases\n- Identifies where the technology reduces risk or cost\n\n## 6. TRL & SBIR Mapping\n- TRL: 1\n- SBIR: Pre-Phase I\n\n## 7. Risks & Mitigations\n- **Risk:** Outdated scientific assumptions\n  **Mitigation:** Annual refresh\n- **Risk:** Overgeneralization\n  **Mitigation:** Peer review\n\n## 8. Change Log\n- 2026-05-17 — Initial scan completed\n"""
file_contents["CIS-A3-CHS_Concept_Hypothesis_Sheet.md"] = """# Concept Hypothesis Sheet\n\n**Document ID:** CIS-A3-CHS\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-2\n**TRL Target:** 1–2\n**Grid Slot:** U-003\n**PRECISELIENS Node:** Glass-2\n\n---\n\n## 1. Purpose\nDefine the core mechanism, expected performance envelope, and conceptual behavior of the technology.\n\n## 2. Inputs\n- Problem Definition Matrix\n- Scientific Foundations Scan\n- Mission constraints\n\n## 3. Outputs\n- Hypothesis card\n- Expected performance envelope\n- Initial assumptions list\n\n## 4. Method\n1. Identify core mechanism\n2. Define expected behavior\n3. Establish bounding assumptions\n4. Validate conceptual coherence\n\n## 5. Mission Integration\n- Identifies mission phases where the concept applies\n- Establishes early interface assumptions\n\n## 6. TRL & SBIR Mapping\n- TRL: 1–2\n- SBIR: Pre-Phase I\n\n## 7. Risks & Mitigations\n- **Risk:** Incorrect assumptions\n  **Mitigation:** Track assumptions explicitly\n- **Risk:** Overly optimistic performance envelope\n  **Mitigation:** Use conservative bounds\n\n## 8. Change Log\n- 2026-05-17 — Hypothesis defined\n"""
file_contents["CIS-A4-FEM_Feasibility_Envelope_Model.md"] = """# Feasibility Envelope Model\n\n**Document ID:** CIS-A4-FEM\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-3\n**TRL Target:** 2\n**Grid Slot:** U-004\n**PRECISELIENS Node:** Glass-3\n\n---\n\n## 1. Purpose\nModel the feasibility bounds of the concept using early simulations and analytical methods.\n\n## 2. Inputs\n- Hypothesis Sheet\n- Scientific principles\n- Mission constraints\n- Environmental parameters\n\n## 3. Outputs\n- Feasibility envelope\n- Boundary conditions\n- Risk surfaces\n- Sensitivity analysis\n\n## 4. Method\n1. Identify key variables\n2. Build analytical or low-fidelity simulation models\n3. Sweep parameter space\n4. Identify feasibility regions\n\n## 5. Mission Integration\n- Determines whether the concept survives lunar environmental extremes\n- Identifies required shielding, power, or thermal controls\n\n## 6. TRL & SBIR Mapping\n- TRL: 2\n- SBIR: Pre-Phase I\n\n## 7. Risks & Mitigations\n- **Risk:** Model oversimplification\n  **Mitigation:** Document assumptions\n- **Risk:** Missing environmental factors\n  **Mitigation:** Cross-check with mission environment data\n\n## 8. Change Log\n- 2026-05-17 — Envelope established\n"""
file_contents["CIS-A5-UID_Umbrella_Integration_Draft.md"] = """# Umbrella Integration Draft\n\n**Document ID:** CIS-A5-UID\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-4\n**TRL Target:** 2\n**Grid Slot:** U-005\n**PRECISELIENS Node:** Glass-4\n\n---\n\n## 1. Purpose\nIntegrate the concept into the CIS Umbrella taxonomy, establishing lineage, classification, and governance.\n\n## 2. Inputs\n- Problem Definition Matrix\n- Feasibility Envelope\n- Hypothesis Sheet\n\n## 3. Outputs\n- Umbrella lineage map\n- Classification tags\n- Governance notes\n- Dependency graph\n\n## 4. Method\n1. Identify CIS category\n2. Map dependencies\n3. Define governance rules\n4. Establish lineage and naming\n\n## 5. Mission Integration\n- Ensures compatibility with CIS-wide architecture\n- Establishes early mission governance hooks\n\n## 6. TRL & SBIR Mapping\n- TRL: 2\n- SBIR: Pre-Phase I\n\n## 7. Risks & Mitigations\n- **Risk:** Misclassification\n  **Mitigation:** Umbrella review board\n- **Risk:** Missing dependencies\n  **Mitigation:** Cross-layer audit\n\n## 8. Change Log\n- 2026-05-17 — Umbrella integration drafted\n"""

# B1 - B5
file_contents["CIS-B1-PAB_Preliminary_Architecture_Blueprint.md"] = """# Preliminary Architecture Blueprint\n\n**Document ID:** CIS-B1-PAB\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-5\n**TRL Target:** 2–3\n**Grid Slot:** M-010\n**PRECISELIENS Node:** Mirror-0\n\n---\n\n## 1. Purpose\nDefine the initial system architecture, including functional blocks, data flows, interfaces, and constraints. Establish the structural foundation for all prototypes.\n\n## 2. Inputs\n- Umbrella Integration Draft\n- Feasibility Envelope Model\n- Mission constraints\n- Early performance envelope\n\n## 3. Outputs\n- System block diagram\n- Data flow diagrams\n- Interface definitions\n- Architectural assumptions list\n\n## 4. Method\n1. Identify core system functions\n2. Group functions into architectural blocks\n3. Define data and control flows\n4. Establish interface boundaries\n5. Validate against mission constraints\n\n## 5. Mission Integration\n- Identifies which mission systems the architecture must interface with\n- Establishes early comms, power, and data assumptions\n- Ensures compatibility with Artemis/Gateway infrastructure\n\n## 6. TRL & SBIR Mapping\n- TRL: 2–3\n- SBIR: Pre-Phase I → Phase I transition\n\n## 7. Risks & Mitigations\n- **Risk:** Architecture diverges from mission constraints\n  **Mitigation:** Early mission integration reviews\n- **Risk:** Overcomplexity\n  **Mitigation:** Enforce minimal viable architecture\n\n## 8. Change Log\n- 2026-05-17 — Architecture baseline created\n"""
file_contents["CIS-B2-MBL_Mirror_Base_Lattice_Map.md"] = """# Mirror/Base Lattice Map\n\n**Document ID:** CIS-B2-MBL\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-6\n**TRL Target:** 2–3\n**Grid Slot:** M-011\n**PRECISELIENS Node:** Mirror-1\n\n---\n\n## 1. Purpose\nMap architectural components into the PLLC Mirror/Base lattice, defining stable logic, core services, and deterministic behaviors.\n\n## 2. Inputs\n- Architecture Blueprint\n- Umbrella lineage\n- Mission constraints\n\n## 3. Outputs\n- Mirror/Base lattice diagram\n- Component placement rationale\n- Stability classification\n- Dependency mapping\n\n## 4. Method\n1. Identify stable vs. dynamic components\n2. Assign stable components to Mirror nodes\n3. Assign dynamic or reactive components to Base nodes\n4. Validate lattice coherence\n\n## 5. Mission Integration\n- Ensures deterministic behavior for mission-critical functions\n- Establishes which components require redundancy\n- Supports mission safety analysis\n\n## 6. TRL & SBIR Mapping\n- TRL: 2–3\n- SBIR: Pre-Phase I → Phase I\n\n## 7. Risks & Mitigations\n- **Risk:** Misclassification of stability\n  **Mitigation:** Stress-test assumptions\n- **Risk:** Lattice imbalance\n  **Mitigation:** Redistribute load across nodes\n\n## 8. Change Log\n- 2026-05-17 — Lattice mapping completed\n"""
file_contents["CIS-B3-A0R_Prototype_Alpha0_Report.md"] = """# Prototype Alpha-0 Report\n\n**Document ID:** CIS-B3-A0R\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-7\n**TRL Target:** 2–3\n**Grid Slot:** M-012\n**PRECISELIENS Node:** Mirror-2\n\n---\n\n## 1. Purpose\nDocument the first minimal functional prototype demonstrating the core mechanism under controlled conditions.\n\n## 2. Inputs\n- Architecture Blueprint\n- Lattice Map\n- Feasibility Envelope\n\n## 3. Outputs\n- Alpha-0 design description\n- Implementation notes\n- Initial performance observations\n- Prototype limitations list\n\n## 4. Method\n1. Implement minimal viable architecture\n2. Conduct basic functional tests\n3. Compare results to feasibility bounds\n4. Document deviations and anomalies\n\n## 5. Mission Integration\n- Identifies early mission functions touched by the prototype\n- Highlights interface assumptions requiring validation\n- Establishes early performance expectations\n\n## 6. TRL & SBIR Mapping\n- TRL: 2–3\n- SBIR: Pre-Phase I → Phase I candidate\n\n## 7. Risks & Mitigations\n- **Risk:** Prototype overfits lab conditions\n  **Mitigation:** Document environmental assumptions\n- **Risk:** Architecture drift\n  **Mitigation:** Trace each component back to PAB\n\n## 8. Change Log\n- 2026-05-17 — Alpha-0 baseline documented\n"""
file_contents["CIS-B4-RFMA_Risk_Failure_Mode_Atlas.md"] = """# Risk & Failure Mode Atlas\n\n**Document ID:** CIS-B4-RFMA\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-8\n**TRL Target:** 3\n**Grid Slot:** M-013\n**PRECISELIENS Node:** Mirror-3\n\n---\n\n## 1. Purpose\nIdentify, classify, and analyze risks and failure modes across the system, including lunar environmental stressors.\n\n## 2. Inputs\n- Alpha-0 Report\n- Architecture Blueprint\n- Mission constraints\n- Environmental data\n\n## 3. Outputs\n- Failure Mode and Effects Analysis (FMEA)\n- Risk matrix\n- Environmental stressor map\n- Mitigation strategies\n\n## 4. Method\n1. Enumerate components and interfaces\n2. Identify failure modes\n3. Assess severity, likelihood, detectability\n4. Map environmental stressors\n5. Define mitigations\n\n## 5. Mission Integration\n- Identifies mission-critical vulnerabilities\n- Supports safety and redundancy planning\n- Informs Phase I test design\n\n## 6. TRL & SBIR Mapping\n- TRL: 3\n- SBIR: Phase I preparation\n\n## 7. Risks & Mitigations\n- **Risk:** Undiscovered failure modes\n  **Mitigation:** Cross-discipline review\n- **Risk:** Underestimated environmental effects\n  **Mitigation:** Conservative modeling\n\n## 8. Change Log\n- 2026-05-17 — RFMA baseline created\n"""
file_contents["CIS-B5-SP1G_SBIR_Phase1_Readiness_Gate.md"] = """# SBIR Phase I Readiness Gate\n\n**Document ID:** CIS-B5-SP1G\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-9\n**TRL Target:** 3–4\n**Grid Slot:** M-014\n**PRECISELIENS Node:** Mirror-4\n\n---\n\n## 1. Purpose\nConfirm readiness for SBIR Phase I proposal submission, ensuring technical, mission, and architectural alignment.\n\n## 2. Inputs\n- RFMA\n- Alpha-0 Report\n- Architecture Blueprint\n- Mission need statement\n\n## 3. Outputs\n- Phase I compliance packet\n- Technical narrative\n- Workplan outline\n- Risk posture summary\n\n## 4. Method\n1. Validate technical feasibility\n2. Confirm mission alignment\n3. Assemble compliance documentation\n4. Conduct internal readiness review\n\n## 5. Mission Integration\n- Ensures proposal aligns with NASA mission priorities\n- Establishes early mission integration hooks\n- Confirms feasibility under lunar constraints\n\n## 6. TRL & SBIR Mapping\n- TRL: 3–4\n- SBIR: Phase I entry\n\n## 7. Risks & Mitigations\n- **Risk:** Proposal misalignment\n  **Mitigation:** Review against solicitation language\n- **Risk:** Missing compliance elements\n  **Mitigation:** Use SBIR compliance checklist\n\n## 8. Change Log\n- 2026-05-17 — Phase I readiness confirmed\n"""

# C1 - C5
file_contents["CIS-C1-P1WA_Phase1_Workplan_Activation.md"] = """# Phase I Workplan Activation\n\n**Document ID:** CIS-C1-P1WA\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-10\n**TRL Target:** 3–4\n**Grid Slot:** M-020\n**PRECISELIENS Node:** Mirror-5\n\n---\n\n## 1. Purpose\nActivate the SBIR Phase I workplan, defining milestones, deliverables, cadence, and success criteria for the proof-of-concept period.\n\n## 2. Inputs\n- SBIR Phase I Readiness Gate\n- Architecture Blueprint\n- RFMA\n- Mission need statement\n\n## 3. Outputs\n- Phase I milestone schedule\n- Deliverable list\n- Resource allocation\n- Review cadence (internal + external)\n\n## 4. Method\n1. Translate solicitation requirements into actionable tasks\n2. Define milestone sequence\n3. Assign resources and responsibilities\n4. Establish review checkpoints\n5. Validate feasibility within Phase I constraints\n\n## 5. Mission Integration\n- Ensures Phase I tasks align with mission priorities\n- Establishes early mission-ops touchpoints\n- Identifies data needed for Phase II justification\n\n## 6. TRL & SBIR Mapping\n- TRL: 3 → 4\n- SBIR: Phase I execution\n\n## 7. Risks & Mitigations\n- **Risk:** Overambitious milestone pacing\n  **Mitigation:** Prioritize minimum viable demonstrations\n- **Risk:** Misalignment with solicitation\n  **Mitigation:** Weekly compliance checks\n\n## 8. Change Log\n- 2026-05-17 — Phase I workplan activated\n"""
file_contents["CIS-C2-A1R_Prototype_Alpha1_Report.md"] = """# Prototype Alpha-1 Report\n\n**Document ID:** CIS-C2-A1R\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-11\n**TRL Target:** 3–4\n**Grid Slot:** M-021\n**PRECISELIENS Node:** Mirror-6\n\n---\n\n## 1. Purpose\nDocument the Alpha-1 prototype, the first Phase I demonstration of functional capability under controlled but realistic conditions.\n\n## 2. Inputs\n- Alpha-0 Report\n- Phase I Workplan\n- Updated architectural assumptions\n- RFMA\n\n## 3. Outputs\n- Alpha-1 design description\n- Test results\n- Performance deltas vs. Alpha-0\n- Updated limitations list\n\n## 4. Method\n1. Implement Phase I feature set\n2. Conduct functional and environmental tests\n3. Compare results to Alpha-0 baseline\n4. Document anomalies and insights\n\n## 5. Mission Integration\n- Identifies which mission functions Alpha-1 can now support\n- Establishes early interface behavior\n- Provides data for Phase II justification\n\n## 6. TRL & SBIR Mapping\n- TRL: 3–4\n- SBIR: Phase I mid-stage\n\n## 7. Risks & Mitigations\n- **Risk:** Prototype instability\n  **Mitigation:** Add fallback logic in Mirror layer\n- **Risk:** Environmental mismatch\n  **Mitigation:** Increase fidelity of test conditions\n\n## 8. Change Log\n- 2026-05-17 — Alpha-1 baseline documented\n"""
file_contents["CIS-C3-EVL_Experimental_Validation_Log.md"] = """# Experimental Validation Log\n\n**Document ID:** CIS-C3-EVL\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-12\n**TRL Target:** 4\n**Grid Slot:** M-022\n**PRECISELIENS Node:** Mirror-7\n\n---\n\n## 1. Purpose\nRecord all experimental tests, results, anomalies, and validation outcomes for Phase I.\n\n## 2. Inputs\n- Alpha-1 prototype\n- Phase I test plan\n- Environmental parameters\n- RFMA\n\n## 3. Outputs\n- Test logs\n- Validation summaries\n- Anomaly reports\n- Updated risk posture\n\n## 4. Method\n1. Execute Phase I test matrix\n2. Log all results with timestamps\n3. Identify anomalies and classify severity\n4. Validate performance against feasibility envelope\n5. Update risk posture\n\n## 5. Mission Integration\n- Provides evidence of performance under mission-like conditions\n- Supports Phase II proposal with quantitative data\n- Identifies mission-critical failure modes\n\n## 6. TRL & SBIR Mapping\n- TRL: 4\n- SBIR: Phase I validation\n\n## 7. Risks & Mitigations\n- **Risk:** Incomplete test coverage\n  **Mitigation:** Cross-check against RFMA\n- **Risk:** Data inconsistency\n  **Mitigation:** Use standardized logging format\n\n## 8. Change Log\n- 2026-05-17 — Validation log initiated\n"""
file_contents["CIS-C4-MID_Mission_Interface_Draft.md"] = """# Mission Interface Draft\n\n**Document ID:** CIS-C4-MID\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-13\n**TRL Target:** 4\n**Grid Slot:** M-023\n**PRECISELIENS Node:** Mirror-8\n\n---\n\n## 1. Purpose\nDefine the preliminary mission interfaces for the technology, including data, power, comms, mechanical, and operational touchpoints.\n\n## 2. Inputs\n- Architecture Blueprint\n- Alpha-1 Report\n- Validation Log\n- Mission constraints\n\n## 3. Outputs\n- Interface definitions\n- Data schemas\n- Power and comms requirements\n- Operational assumptions\n\n## 4. Method\n1. Identify mission systems requiring integration\n2. Define interface boundaries\n3. Establish data and control schemas\n4. Validate against mission constraints\n\n## 5. Mission Integration\n- Establishes compatibility with Artemis/Gateway systems\n- Identifies required interface hardware/software\n- Supports Phase II integration planning\n\n## 6. TRL & SBIR Mapping\n- TRL: 4\n- SBIR: Phase I integration planning\n\n## 7. Risks & Mitigations\n- **Risk:** Interface mismatch with mission systems\n  **Mitigation:** Early mission integration reviews\n- **Risk:** Underestimated power/comms needs\n  **Mitigation:** Conservative budgeting\n\n## 8. Change Log\n- 2026-05-17 — Mission interface drafted\n"""
file_contents["CIS-C5-P1CA_Phase1_Closeout_TRL_Audit.md"] = """# Phase I Closeout & TRL Audit\n\n**Document ID:** CIS-C5-P1CA\n**CIS Layer:** PLLC\n**Centauri Phase:** Centauri-14\n**TRL Target:** 4\n**Grid Slot:** M-024\n**PRECISELIENS Node:** Mirror-9\n\n---\n\n## 1. Purpose\nClose out SBIR Phase I, confirm TRL 4 achievement, and prepare the technical basis for Phase II proposal submission.\n\n## 2. Inputs\n- Validation Log\n- Mission Interface Draft\n- Alpha-1 Report\n- Phase I Workplan\n\n## 3. Outputs\n- TRL 4 confirmation\n- Phase I final report\n- Phase II justification package\n- Updated risk posture\n\n## 4. Method\n1. Review all Phase I results\n2. Confirm TRL 4 criteria\n3. Document lessons learned\n4. Prepare Phase II justification materials\n\n## 5. Mission Integration\n- Confirms mission relevance\n- Identifies integration tasks for Phase II\n- Establishes readiness for engineering development\n\n## 6. TRL & SBIR Mapping\n- TRL: 4\n- SBIR: Phase I closeout → Phase II entry\n\n## 7. Risks & Mitigations\n- **Risk:** Insufficient evidence for TRL 4\n  **Mitigation:** Supplement with additional tests\n- **Risk:** Weak Phase II justification\n  **Mitigation:** Strengthen mission alignment narrative\n\n## 8. Change Log\n- 2026-05-17 — Phase I closeout completed\n"""

# D1 - D5
file_contents["CIS-D1-P2SEP_Phase2_Systems_Engineering_Plan.md"] = """# Phase II Systems Engineering Plan\n\n**Document ID:** CIS-D1-P2SEP\n**CIS Layer:** PLLLC\n**Centauri Phase:** Centauri-15\n**TRL Target:** 4–5\n**Grid Slot:** G-030\n**PRECISELIENS Node:** Pass-0\n\n---\n\n## 1. Purpose\nDefine the full engineering roadmap for SBIR Phase II, including system requirements, verification plans, integration strategy, and mission-aligned development pathways.\n\n## 2. Inputs\n- Phase I Closeout & TRL Audit\n- Mission Interface Draft\n- Updated architectural assumptions\n- RFMA\n\n## 3. Outputs\n- Engineering requirements\n- Verification & validation (V&V) plan\n- Integration roadmap\n- Updated risk posture\n- Phase II milestone schedule\n\n## 4. Method\n1. Translate mission needs into engineering requirements\n2. Define V&V strategy\n3. Establish integration sequence\n4. Identify long-lead items\n5. Validate feasibility within Phase II constraints\n\n## 5. Mission Integration\n- Aligns engineering tasks with Artemis/Gateway integration points\n- Defines mission-critical interfaces\n- Establishes environmental qualification pathway\n\n## 6. TRL & SBIR Mapping\n- TRL: 4 → 5\n- SBIR: Phase II initiation\n\n## 7. Risks & Mitigations\n- **Risk:** Requirements creep\n  **Mitigation:** Freeze baseline with controlled change process\n- **Risk:** Underestimated integration complexity\n  **Mitigation:** Early interface prototyping\n\n## 8. Change Log\n- 2026-05-17 — Phase II SEP established\n"""
file_contents["CIS-D2-B0R_Prototype_Beta0_Report.md"] = """# Prototype Beta-0 Report\n\n**Document ID:** CIS-D2-B0R\n**CIS Layer:** PLLLC\n**Centauri Phase:** Centauri-16\n**TRL Target:** 5\n**Grid Slot:** G-031\n**PRECISELIENS Node:** Pass-1\n\n---\n\n## 1. Purpose\nDocument the Beta-0 prototype, the first engineering-grade implementation demonstrating stable, repeatable behavior under relevant environmental conditions.\n\n## 2. Inputs\n- Phase II SEP\n- Alpha-1 results\n- Updated architectural assumptions\n- Mission Interface Draft\n\n## 3. Outputs\n- Beta-0 design description\n- Engineering test results\n- Environmental performance data\n- Updated limitations and risks\n\n## 4. Method\n1. Implement engineering-grade architecture\n2. Conduct functional, environmental, and stress tests\n3. Compare results to Phase I performance\n4. Document anomalies and engineering insights\n\n## 5. Mission Integration\n- Demonstrates readiness for mission-relevant environments\n- Establishes baseline for environmental qualification\n- Validates interface assumptions\n\n## 6. TRL & SBIR Mapping\n- TRL: 5\n- SBIR: Phase II mid-stage\n\n## 7. Risks & Mitigations\n- **Risk:** Engineering instability\n  **Mitigation:** Add redundancy and error-handling\n- **Risk:** Environmental mismatch\n  **Mitigation:** Increase fidelity of test chambers\n\n## 8. Change Log\n- 2026-05-17 — Beta-0 baseline documented\n"""
file_contents["CIS-D3-PGMIS_Pass_Glass_Morphism_Integration_Spec.md"] = """# Pass/Glass Morphism Integration Spec\n\n**Document ID:** CIS-D3-PGMIS\n**CIS Layer:** PLLLC\n**Centauri Phase:** Centauri-17\n**TRL Target:** 5–6\n**Grid Slot:** G-032\n**PRECISELIENS Node:** Pass-2\n\n---\n\n## 1. Purpose\nDefine how internal system states, transitions, and behaviors are exposed through pass/glass morphisms for visualization, debugging, and mission-ops transparency.\n\n## 2. Inputs\n- Phase II SEP\n- Beta-0 Report\n- PRECISELIENS schema\n- Mission Interface Draft\n\n## 3. Outputs\n- State → visualization mapping\n- Morphism rules\n- Data contracts for visualization layers\n- Latency and performance constraints\n\n## 4. Method\n1. Enumerate internal states and transitions\n2. Classify states as visible, aggregated, or hidden\n3. Define morphism rules for each state\n4. Validate performance and security constraints\n\n## 5. Mission Integration\n- Enables mission control to visualize system health\n- Supports anomaly investigation\n- Provides transparency for safety-critical operations\n\n## 6. TRL & SBIR Mapping\n- TRL: 5–6\n- SBIR: Phase II visualization integration\n\n## 7. Risks & Mitigations\n- **Risk:** Overexposure of sensitive internals\n  **Mitigation:** Role-based visibility and redaction\n- **Risk:** Visualization lag\n  **Mitigation:** Define latency budgets and test them\n\n## 8. Change Log\n- 2026-05-17 — Morphism spec drafted\n"""
file_contents["CIS-D4-EQP_Environmental_Qualification_Pathway.md"] = """# Environmental Qualification Pathway\n\n**Document ID:** CIS-D4-EQP\n**CIS Layer:** PLLLC\n**Centauri Phase:** Centauri-18\n**TRL Target:** 5–6\n**Grid Slot:** G-033\n**PRECISELIENS Node:** Pass-3\n\n---\n\n## 1. Purpose\nDefine the environmental qualification plan required to validate the system for lunar mission deployment.\n\n## 2. Inputs\n- Beta-0 Report\n- Phase II SEP\n- Mission environmental data\n- RFMA\n\n## 3. Outputs\n- Environmental test matrix\n- Qualification criteria\n- Stressor mapping\n- Test facility requirements\n\n## 4. Method\n1. Identify environmental stressors (thermal, vacuum, dust, radiation)\n2. Define qualification thresholds\n3. Build test matrix\n4. Validate feasibility with test facilities\n\n## 5. Mission Integration\n- Ensures system can survive lunar environment\n- Supports mission safety certification\n- Establishes environmental margins\n\n## 6. TRL & SBIR Mapping\n- TRL: 5–6\n- SBIR: Phase II environmental qualification\n\n## 7. Risks & Mitigations\n- **Risk:** Underestimated stressor severity\n  **Mitigation:** Conservative margins\n- **Risk:** Facility limitations\n  **Mitigation:** Multi-site testing\n\n## 8. Change Log\n- 2026-05-17 — EQP established\n"""
file_contents["CIS-D5-MOSTL_Mission_Ops_Simulation_Trial_Log.md"] = """# Mission Ops Simulation Trial Log\n\n**Document ID:** CIS-D5-MOSTL\n**CIS Layer:** PLLLC\n**Centauri Phase:** Centauri-19\n**TRL Target:** 6\n**Grid Slot:** G-034\n**PRECISELIENS Node:** Pass-4\n\n---\n\n## 1. Purpose\nRecord results from mission-ops simulations integrating the system with NBS‑1 Data Voyager, Cloud One Templates, and CIS infrastructure.\n\n## 2. Inputs\n- Beta-0 prototype\n- Mission Interface Draft\n- Environmental Qualification Pathway\n- PRECISELIENS morphism rules\n\n## 3. Outputs\n- Simulation logs\n- Mission behavior analysis\n- Anomaly reports\n- Updated integration assumptions\n\n## 4. Method\n1. Integrate system into mission simulation environment\n2. Execute operational scenarios\n3. Log system behavior and anomalies\n4. Validate mission compatibility\n\n## 5. Mission Integration\n- Confirms operational readiness\n- Identifies mission-critical behaviors\n- Supports Phase III planning\n\n## 6. TRL & SBIR Mapping\n- TRL: 6\n- SBIR: Phase II → Phase III transition\n\n## 7. Risks & Mitigations\n- **Risk:** Simulation fidelity mismatch\n  **Mitigation:** Validate against real mission data\n- **Risk:** Integration anomalies\n  **Mitigation:** Add fallback logic and redundancy\n\n## 8. Change Log\n- 2026-05-17 — MOSTL initiated\n"""

# E1 - E5
file_contents["CIS-E1-B1R_Prototype_Beta1_Report.md"] = """# Prototype Beta-1 Report\n\n**Document ID:** CIS-E1-B1R\n**CIS Layer:** Extended Infrastructure\n**Centauri Phase:** Centauri-20\n**TRL Target:** 6–7\n**Grid Slot:** X-040\n**PRECISELIENS Node:** Render-0\n\n---\n\n## 1. Purpose\nDocument the Beta‑1 prototype, a near‑flight engineering model demonstrating stable, repeatable behavior in mission‑relevant environments.\n\n## 2. Inputs\n- Beta‑0 Report\n- Mission Ops Simulation Trial Log\n- Environmental Qualification Pathway\n- Updated architectural assumptions\n\n## 3. Outputs\n- Beta‑1 design description\n- Environmental performance data\n- Stress test results\n- Updated risk posture\n\n## 4. Method\n1. Implement near‑flight architecture\n2. Conduct high‑fidelity environmental tests\n3. Validate interface behavior\n4. Document anomalies and engineering insights\n\n## 5. Mission Integration\n- Demonstrates readiness for lunar deployment\n- Validates mission‑critical interfaces\n- Supports Phase III certification\n\n## 6. TRL & SBIR Mapping\n- TRL: 6 → 7\n- SBIR: Late Phase II\n\n## 7. Risks & Mitigations\n- **Risk:** Environmental drift\n  **Mitigation:** Increase test fidelity\n- **Risk:** Interface instability\n  **Mitigation:** Add redundancy and fallback logic\n\n## 8. Change Log\n- 2026-05-17 — Beta‑1 baseline documented\n"""
file_contents["CIS-E2-EILM_Extended_Infrastructure_Layer_Map.md"] = """# Extended Infrastructure Layer Map\n\n**Document ID:** CIS-E2-EILM\n**CIS Layer:** Extended Infrastructure\n**Centauri Phase:** Centauri-21\n**TRL Target:** 6–7\n**Grid Slot:** X-041\n**PRECISELIENS Node:** Render-1\n\n---\n\n## 1. Purpose\nMap the system into the Extended Infrastructure layer, including pipelines, rendering engines, supply chain, telemetry, and the 10,000‑core grid.\n\n## 2. Inputs\n- Beta‑1 Report\n- Mission Ops Simulation Trial Log\n- CIS Umbrella lineage\n- PRECISELIENS schema\n\n## 3. Outputs\n- Extended Infrastructure map\n- Grid slot assignments\n- Pipeline definitions\n- Telemetry schema\n\n## 4. Method\n1. Identify infrastructure dependencies\n2. Assign components to grid slots\n3. Define pipelines and data flows\n4. Validate mission‑ops compatibility\n\n## 5. Mission Integration\n- Ensures compatibility with mission telemetry\n- Establishes supply chain and deployment pathways\n- Supports mission‑ops visualization\n\n## 6. TRL & SBIR Mapping\n- TRL: 6–7\n- SBIR: Late Phase II\n\n## 7. Risks & Mitigations\n- **Risk:** Grid congestion\n  **Mitigation:** Load balancing\n- **Risk:** Pipeline bottlenecks\n  **Mitigation:** Parallelization\n\n## 8. Change Log\n- 2026-05-17 — EILM created\n"""
file_contents["CIS-E3-MSSTR_Mission_Scenario_Stress_Test_Report.md"] = """# Mission Scenario Stress Test Report\n\n**Document ID:** CIS-E3-MSSTR\n**CIS Layer:** Extended Infrastructure\n**Centauri Phase:** Centauri-22\n**TRL Target:** 6–7\n**Grid Slot:** X-042\n**PRECISELIENS Node:** Render-2\n\n---\n\n## 1. Purpose\nDocument results from mission scenario stress tests, including EVA, comms delay, dust exposure, thermal cycling, and operational anomalies.\n\n## 2. Inputs\n- Beta‑1 prototype\n- Environmental Qualification Pathway\n- Mission Ops Simulation Trial Log\n- Mission constraints\n\n## 3. Outputs\n- Stress test logs\n- Anomaly reports\n- Updated risk posture\n- Mission behavior analysis\n\n## 4. Method\n1. Execute mission scenarios\n2. Log system behavior\n3. Identify anomalies\n4. Validate mission compatibility\n\n## 5. Mission Integration\n- Confirms system behavior under mission‑like stress\n- Identifies mission‑critical vulnerabilities\n- Supports Phase III certification\n\n## 6. TRL & SBIR Mapping\n- TRL: 6–7\n- SBIR: Late Phase II\n\n## 7. Risks & Mitigations\n- **Risk:** Unmodeled mission stressors\n  **Mitigation:** Expand scenario set\n- **Risk:** Interface failures\n  **Mitigation:** Add redundancy\n\n## 8. Change Log\n- 2026-05-17 — MSSTR completed\n"""
file_contents["CIS-E4-LORR1_Lunar_Ops_Readiness_Review.md"] = """# Lunar Ops Readiness Review (LORR-1)\n\n**Document ID:** CIS-E4-LORR1\n**CIS Layer:** Extended Infrastructure\n**Centauri Phase:** Centauri-23\n**TRL Target:** 7\n**Grid Slot:** X-043\n**PRECISELIENS Node:** Render-3\n\n---\n\n## 1. Purpose\nConduct a NASA‑style readiness review confirming the system’s suitability for lunar operations.\n\n## 2. Inputs\n- Stress Test Report\n- Extended Infrastructure Layer Map\n- Beta‑1 Report\n- Mission Interface Draft\n\n## 3. Outputs\n- Readiness assessment\n- Risk posture\n- Required mitigations\n- Go/No‑Go recommendation\n\n## 4. Method\n1. Review all upstream artifacts\n2. Confirm TRL 7 criteria\n3. Identify remaining risks\n4. Issue readiness recommendation\n\n## 5. Mission Integration\n- Confirms compatibility with Artemis mission phases\n- Establishes operational constraints\n- Supports Phase III certification\n\n## 6. TRL & SBIR Mapping\n- TRL: 7\n- SBIR: Phase II → Phase III transition\n\n## 7. Risks & Mitigations\n- **Risk:** Unresolved mission‑critical risks\n  **Mitigation:** Additional testing\n- **Risk:** Integration drift\n  **Mitigation:** Freeze interfaces\n\n## 8. Change Log\n- 2026-05-17 — LORR‑1 completed\n"""
file_contents["CIS-E5-CVD_Commercialization_Vector_Draft.md"] = """# Commercialization Vector Draft\n\n**Document ID:** CIS-E5-CVD\n**CIS Layer:** Extended Infrastructure\n**Centauri Phase:** Centauri-24\n**TRL Target:** 7\n**Grid Slot:** X-044\n**PRECISELIENS Node:** Render-4\n\n---\n\n## 1. Purpose\nDefine commercialization pathways, acquisition channels, licensing models, and scaling strategies.\n\n## 2. Inputs\n- LORR‑1\n- Stress Test Report\n- Extended Infrastructure Layer Map\n- Mission need statement\n\n## 3. Outputs\n- Commercialization pathways\n- Acquisition strategy\n- Licensing model\n- Scaling plan\n\n## 4. Method\n1. Identify target markets\n2. Define acquisition channels\n3. Establish licensing and IP strategy\n4. Build scaling roadmap\n\n## 5. Mission Integration\n- Ensures commercial viability for mission deployment\n- Supports Phase III funding\n- Aligns with NASA acquisition pathways\n\n## 6. TRL & SBIR Mapping\n- TRL: 7\n- SBIR: Phase III preparation\n\n## 7. Risks & Mitigations\n- **Risk:** Market misalignment\n  **Mitigation:** Conduct market validation\n- **Risk:** Supply chain fragility\n  **Mitigation:** Multi‑vendor strategy\n\n## 8. Change Log\n- 2026-05-17 — CVD drafted\n"""

# F1 - F5
file_contents["CIS-F1-G0R_Prototype_Gamma0_Report.md"] = """# Prototype Gamma-0 Report\n\n**Document ID:** CIS-F1-G0R\n**CIS Layer:** Extended → Umbrella\n**Centauri Phase:** Centauri-25\n**TRL Target:** 7–8\n**Grid Slot:** X-050\n**PRECISELIENS Node:** Apex-0\n\n---\n\n## 1. Purpose\nDocument the Gamma‑0 prototype, the first flight‑capable implementation demonstrating full system behavior under mission‑representative conditions.\n\n## 2. Inputs\n- Beta‑1 Report\n- LORR‑1\n- Extended Infrastructure Layer Map\n- Mission Scenario Stress Test Report\n\n## 3. Outputs\n- Gamma‑0 design description\n- Flight‑capable configuration\n- Environmental qualification results\n- Updated risk posture\n\n## 4. Method\n1. Implement flight‑capable architecture\n2. Conduct full environmental qualification\n3. Validate mission interfaces\n4. Document anomalies and final engineering insights\n\n## 5. Mission Integration\n- Confirms readiness for Artemis‑class missions\n- Establishes flight configuration baseline\n- Supports Mission Integration Certification Packet\n\n## 6. TRL & SBIR Mapping\n- TRL: 7 → 8\n- SBIR: Phase III initiation\n\n## 7. Risks & Mitigations\n- **Risk:** Configuration drift\n  **Mitigation:** Freeze flight baseline\n- **Risk:** Environmental edge cases\n  **Mitigation:** Expand qualification margins\n\n## 8. Change Log\n- 2026-05-17 — Gamma‑0 baseline documented\n"""
file_contents["CIS-F2-MICP_Mission_Integration_Certification_Packet.md"] = """# Mission Integration Certification Packet\n\n**Document ID:** CIS-F2-MICP\n**CIS Layer:** Extended → Umbrella\n**Centauri Phase:** Centauri-26\n**TRL Target:** 8\n**Grid Slot:** X-051\n**PRECISELIENS Node:** Apex-1\n\n---\n\n## 1. Purpose\nProvide the certification packet required to integrate the system into Artemis/Gateway mission operations.\n\n## 2. Inputs\n- Gamma‑0 Report\n- LORR‑1\n- Mission Interface Draft\n- Environmental Qualification Pathway\n\n## 3. Outputs\n- Certification checklist\n- Interface compliance report\n- Safety and redundancy analysis\n- Mission integration approval request\n\n## 4. Method\n1. Validate all interfaces\n2. Confirm environmental qualification\n3. Conduct safety and redundancy analysis\n4. Assemble certification packet\n\n## 5. Mission Integration\n- Confirms compatibility with mission systems\n- Establishes operational constraints\n- Supports TRL‑9 certification\n\n## 6. TRL & SBIR Mapping\n- TRL: 8\n- SBIR: Phase III certification\n\n## 7. Risks & Mitigations\n- **Risk:** Certification gaps\n  **Mitigation:** Pre‑review with mission integration team\n- **Risk:** Safety concerns\n  **Mitigation:** Add redundancy and fallback logic\n\n## 8. Change Log\n- 2026-05-17 — MICP assembled\n"""
file_contents["CIS-F3-ODI_Operational_Deployment_Index.md"] = """# Operational Deployment Index\n\n**Document ID:** CIS-F3-ODI\n**CIS Layer:** Extended → Umbrella\n**Centauri Phase:** Centauri-27\n**TRL Target:** 8–9\n**Grid Slot:** X-052\n**PRECISELIENS Node:** Apex-2\n\n---\n\n## 1. Purpose\nDefine the operational deployment procedures, telemetry schemas, and mission‑ops workflows required for flight deployment.\n\n## 2. Inputs\n- Mission Integration Certification Packet\n- Gamma‑0 Report\n- Extended Infrastructure Layer Map\n- Mission constraints\n\n## 3. Outputs\n- Deployment procedures\n- Telemetry schemas\n- Operational workflows\n- Mission‑ops checklists\n\n## 4. Method\n1. Define deployment sequence\n2. Establish telemetry and monitoring schemas\n3. Build operational workflows\n4. Validate with mission‑ops simulation\n\n## 5. Mission Integration\n- Provides mission‑ops with operational procedures\n- Ensures safe deployment and operation\n- Supports TRL‑9 certification\n\n## 6. TRL & SBIR Mapping\n- TRL: 8 → 9\n- SBIR: Phase III deployment\n\n## 7. Risks & Mitigations\n- **Risk:** Operational ambiguity\n  **Mitigation:** Add detailed workflows\n- **Risk:** Telemetry gaps\n  **Mitigation:** Expand monitoring schema\n\n## 8. Change Log\n- 2026-05-17 — ODI created\n"""
file_contents["CIS-F4-CSE_Commercialization_Scaling_Engine.md"] = """# Commercialization & Scaling Engine\n\n**Document ID:** CIS-F4-CSE\n**CIS Layer:** Extended → Umbrella\n**Centauri Phase:** Centauri-28\n**TRL Target:** 9\n**Grid Slot:** X-053\n**PRECISELIENS Node:** Apex-3\n\n---\n\n## 1. Purpose\nDefine the commercialization strategy, scaling plan, manufacturing pathways, and supply chain required for mission‑grade deployment.\n\n## 2. Inputs\n- Operational Deployment Index\n- Mission Integration Certification Packet\n- Commercialization Vector Draft\n- Mission need statement\n\n## 3. Outputs\n- Scaling roadmap\n- Manufacturing plan\n- Supply chain strategy\n- Licensing and acquisition pathways\n\n## 4. Method\n1. Identify manufacturing requirements\n2. Define scaling strategy\n3. Establish supply chain\n4. Validate commercial viability\n\n## 5. Mission Integration\n- Ensures sustainable deployment\n- Supports NASA acquisition pathways\n- Enables long‑term mission support\n\n## 6. TRL & SBIR Mapping\n- TRL: 9\n- SBIR: Phase III commercialization\n\n## 7. Risks & Mitigations\n- **Risk:** Supply chain fragility\n  **Mitigation:** Multi‑vendor strategy\n- **Risk:** Manufacturing bottlenecks\n  **Mitigation:** Parallel production lines\n\n## 8. Change Log\n- 2026-05-17 — CSE drafted\n"""
file_contents["CIS-F5-CAR_Centauri_Apex_Review.md"] = """# Centauri Apex Review\n\n**Document ID:** CIS-F5-CAR\n**CIS Layer:** Umbrella\n**Centauri Phase:** Centauri-29\n**TRL Target:** 9\n**Grid Slot:** U-099\n**PRECISELIENS Node:** Apex-4\n\n---\n\n## 1. Purpose\nProvide the final mission‑grade review confirming TRL‑9 achievement, operational readiness, and full CIS integration.\n\n## 2. Inputs\n- Operational Deployment Index\n- Mission Integration Certification Packet\n- Gamma‑0 Report\n- Commercialization & Scaling Engine\n\n## 3. Outputs\n- TRL‑9 confirmation\n- Final risk posture\n- Go/No‑Go recommendation\n- CIS Umbrella finalization\n\n## 4. Method\n1. Review all upstream artifacts\n2. Confirm TRL‑9 criteria\n3. Validate mission readiness\n4. Issue final recommendation\n\n## 5. Mission Integration\n- Confirms flight‑proven readiness\n- Locks configuration baseline\n- Finalizes CIS lineage\n\n## 6. TRL & SBIR Mapping\n- TRL: 9\n- SBIR: Phase III completion\n\n## 7. Risks & Mitigations\n- **Risk:** Residual unknowns\n  **Mitigation:** Define contingency procedures\n- **Risk:** Configuration drift\n  **Mitigation:** Freeze baselines\n\n## 8. Change Log\n- 2026-05-17 — Apex review completed\n"""

# Build structure
if os.path.exists(root):
    shutil.rmtree(root)
os.makedirs(root)

for section, files in sections.items():
    sec_path = os.path.join(root, section)
    os.makedirs(sec_path)
    for f in files:
        with open(os.path.join(sec_path, f), "w", encoding="utf-8") as out:
            out.write(file_contents[f])

# README
readme = """# CIS Centauri Framework\n30-phase SBIR- and TRL-aligned maturation pipeline integrated with:\n- CIS Umbrella\n- PLLC Mirror/Base\n- PLLLC Pass/Glass Morphism\n- Extended Infrastructure\n- PRECISELIENS visualization layer\n"""
with open(os.path.join(root, "00_README_CENTAURI.md"), "w", encoding="utf-8") as out:
    out.write(readme)

# Move to docs
os.makedirs("docs", exist_ok=True)
if os.path.exists("docs/centauri"):
    shutil.rmtree("docs/centauri")
shutil.move(root, "docs/centauri")

print("Centauri build complete -> docs/centauri/")
