#!/usr/bin/env python3
"""
NetworkBuster SysAdmin Write Tool
Utility for administrators to write formatted logs, reports, and advisories.
"""

import os
import sys
import datetime
from pathlib import Path

def write_log(message, level="INFO"):
    """Write a formatted log message."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] [{level}] {message}\n"
    
    log_file = Path("logs/sysadmin_actions.log")
    log_file.parent.mkdir(exist_ok=True)
    
    with open(log_file, "a") as f:
        f.write(log_entry)
    print(f"Logged: {log_entry.strip()}")

def write_report(title, content, filename=None):
    """Write a formatted markdown report."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if not filename:
        safe_title = title.lower().replace(" ", "_")
        filename = f"reports/sysadmin_{safe_title}.md"
    
    report_path = Path(filename)
    report_path.parent.mkdir(exist_ok=True)
    
    report_content = f"""# {title}
**Date:** {timestamp}
**Author:** System Administrator

---

{content}

---
*Generated by NetworkBuster SysAdmin Write Tool*
"""
    
    with open(report_path, "w") as f:
        f.write(report_content)
    print(f"Report written to: {report_path}")

def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python sysadmin_write.py log <message> [level]")
        print("  python sysadmin_write.py report <title> <content> [filename]")
        return

    cmd = sys.argv[1].lower()
    if cmd == "log" and len(sys.argv) >= 3:
        level = sys.argv[3] if len(sys.argv) > 3 else "INFO"
        write_log(sys.argv[2], level)
    elif cmd == "report" and len(sys.argv) >= 4:
        filename = sys.argv[4] if len(sys.argv) > 4 else None
        write_report(sys.argv[2], sys.argv[3], filename)
    else:
        print("Invalid command or missing arguments.")

if __name__ == "__main__":
    main()
